{% set name = "metis" %}
{% set version = "5.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KarypisLab/METIS/archive/v{{ version }}.tar.gz
  sha256: 1a4665b2cd07edc2f734e30d7460afb19c1217c2547c2ac7bf6e1848d50aff7a
  patches:
    - patches/0004-uncomment-width-variables.patch  # [win]
    # See https://github.com/KarypisLab/METIS/issues/54:
    - getprocvmpeak.diff
    # https://github.com/KarypisLab/METIS/pull/52
    - patches/pr52.patch
    - patches/rusage-win32.patch

build:
  number: 0
  binary_relocation: true
  run_exports:
    - {{ pin_subpackage('metis', max_pin='x.x.x') }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
  host:
    - gklib

test:
  commands:
    - graphchk  # [unix]
    - cmpfillin -h  # [unix]
    - mpmetis -h  # [unix]
    - gpmetis -h  # [unix]
    - ndmetis -h  # [unix]
    - gpmetis -h  # [unix]
    - m2gmetis -h  # [unix]
    - test -f $PREFIX/include/metis.h  # [unix]
    - test -f $PREFIX/lib/libmetis.dylib  # [osx]
    - test -f $PREFIX/lib/libmetis.so  # [linux]
    - if not exist "%LIBRARY_LIB%\\metis.lib" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\graphchk.exe" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\cmpfillin.exe" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\mpmetis.exe" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\gpmetis.exe" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\ndmetis.exe" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\gpmetis.exe" exit 1  # [win]
    - if not exist "%LIBRARY_BIN%\\m2gmetis.exe" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\metis.h" exit 1  # [win]
  source_files:
    - graphs

about:
  home: http://glaros.dtc.umn.edu/gkhome/metis/metis/overview
  license: Apache-2.0
  license_file: LICENSE
  summary: 'METIS - Serial Graph Partitioning and Fill-reducing Matrix Ordering'
  description: |
    METIS is a set of serial programs for partitioning graphs, partitioning
    finite element meshes, and producing fill reducing orderings for sparse
    matrices. The algorithms implemented in METIS are based on the multilevel
    recursive-bisection, multilevel k-way, and multi-constraint partitioning
    schemes developed in our lab.
  doc_url: http://glaros.dtc.umn.edu/gkhome/metis/metis/faq
  dev_url: https://github.com/KarypisLab/METIS.git

extra:
  recipe-maintainers:
    - basnijholt
    - SylvainCorlay
    - mikemhenry
    - matthiasdiener
