appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: oiHhHABZSohWboyr1DKk4D0Io2SSRoFQd54y/dFWaHtodpKfxBpJYzsqc16P4Ps1gJ/JcJ5oSESfzFVDGqdKa6ROgFqwlaPfezqbMqNJd92OXp/obcBcgPTt77Ib60WcAzPxg/tuCn6A0hWElIdg2PYz0tFihP2mEt0QNsLxZc9VeeAbhbgBtQjr/+ER/Az4GnrIPvZttqZ7GUhdi4/kncf9FFHEocqm9nBKCDaLc74dcPjty1JphrtlCirr6xdLs3EdA8nanRM9taXfjgYhUaw5bL3oGBoPDWsoxQjBNzZ0euG3yNcK+PnCVXn0a0uJysGbeJOoLMjsRwNB1jCephl/I/XApyUxcaZ+yD8EAqnLqTEqQ49lgBcbgpWgTnDuIdij74ayfikd0WKdMDAiuqe/tH+LbJUw3x2Fnlqz4y01U2xvbHAKVKtx409dPj0vuupl6B8MWrZslqkbVt+z9tqCucfFVsg/x9xE/ObASDTq5/WzyfHqAz3Dhc2VPzGeIm0FBjinqNtc6F7vwh3EE+m8Kt02ZeXeB+zCqhYefStIl+m/E3dFohqIMCFgXh/2TjNOdA167Ncm2keJXvYtPl09Sv/1j/rxQ5cD44jiRUlap5MerUY1aRDtdyfRImktbUobtvWkqgiWvy6X46wGVo7oyVbgSpKqCThyQ69di/c=}
